#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat $COMMIT_MSG_FILE)

# Regular expression pattern for valid commit messages
PATTERN="^(feature|fix|refactor|wip): .{1,50}$"

if ! [[ $COMMIT_MSG =~ $PATTERN ]]; then
  echo "Error: Invalid commit message format."
  echo "Commit message should be in the format: 'type: message (max 50 characters)'"
  exit 1
fi